import fs from "fs";
import os from "os";
import path from "path";
import crypto from "crypto";

const ATTACHMENT_CAPABILITY = "attachments-v1";
const MAX_BYTES = 5_250_000; // Matches the client: 7 MB base64 below the 8 MiB frame cap.
const MAX_ITEMS = 12; // Includes generated screenshots as well as owner attachments.
const STORE_BYTES = 128 * 1024 * 1024;
// Resolved per call, never memoised at module load. Under CommonJS a test could
// set BROWSER_REMOTE_OBS_DIR in a top-level statement placed above its
// require()s and be sure the assignment ran first. ESM evaluates every import
// before any statement in the importing module, so a load-time constant would
// capture the real ~/zylos/components/browser-remote/observations no matter
// where the test put the assignment -- and the suite would then read and prune
// the live component's store instead of its own temp directory.
function obsDir() {
  return path.resolve(
    process.env.BROWSER_REMOTE_OBS_DIR ||
      path.join(
        os.homedir(),
        "zylos",
        "components",
        "browser-remote",
        "observations",
      ),
  );
}
const materialized = new WeakSet();

// A task owns its files across all decision rounds. Never accept cleanup paths
// from the wire: only files created below enter this scope.
class AttachmentScope {
  constructor() {
    this.files = new Set();
    this.closed = false;
  }
  materialize(value) {
    return materializeAttachments(value, this);
  }
  close() {
    this.closed = true;
    for (const file of this.files) {
      try {
        fs.unlinkSync(file);
      } catch (error) {
        if (error.code !== "ENOENT")
          console.warn(
            `Attachment cleanup failed (${error.code || "IO_ERROR"})`,
          );
      }
    }
    this.files.clear();
  }
}

// Capacity accounting only: files are deleted by their owning task.
function storedAttachmentBytes() {
  const dir = obsDir();
  let names;
  try {
    names = fs.readdirSync(dir);
  } catch (error) {
    if (error.code === "ENOENT") return 0;
    throw error;
  }
  let stored = 0;
  for (const name of names) {
    if (!/^(?:shot|attachment)-/.test(name)) continue;
    const file = path.join(dir, name);
    let stat;
    try {
      stat = fs.lstatSync(file);
      if (!stat.isFile()) continue;
    } catch (error) {
      if (error.code === "ENOENT") continue;
      throw error;
    }
    stored += stat.size;
  }
  return stored;
}

function imageType(bytes) {
  if (bytes.subarray(0, 8).equals(Buffer.from("89504e470d0a1a0a", "hex")))
    return "image/png";
  if (bytes.subarray(0, 3).equals(Buffer.from("ffd8ff", "hex")))
    return "image/jpeg";
  if (["GIF87a", "GIF89a"].includes(bytes.subarray(0, 6).toString("ascii")))
    return "image/gif";
  if (
    bytes.subarray(0, 4).toString("ascii") === "RIFF" &&
    bytes.subarray(8, 12).toString("ascii") === "WEBP"
  )
    return "image/webp";
  return null;
}
function validateBinary(value) {
  const typed = value.type === "image" || value.type === "file";
  if (typed) {
    if (
      typeof value.id !== "string" ||
      !/^[A-Za-z0-9._:-]{1,128}$/.test(value.id) ||
      typeof value.name !== "string" ||
      !value.name ||
      value.name.length > 255 ||
      /[\\/\u0000-\u001f]/.test(value.name) ||
      typeof value.mimeType !== "string" ||
      value.mimeType.length > 128 ||
      !/^[a-z0-9!#$&^_.+-]+\/[a-z0-9!#$&^_.+-]+$/.test(value.mimeType) ||
      !Number.isInteger(value.bytes) ||
      value.bytes < 1 ||
      value.bytes > MAX_BYTES ||
      Object.keys(value).some(
        (key) =>
          !["id", "type", "name", "mimeType", "bytes", "data"].includes(key),
      )
    )
      throw new Error("Invalid attachment metadata");
  }
  if (
    typeof value.data !== "string" ||
    !value.data.length ||
    value.data.length > 7_000_000 ||
    value.data.length % 4 ||
    !/^[A-Za-z0-9+/]+={0,2}$/.test(value.data)
  )
    throw new Error("Invalid attachment encoding");
  const bytes = Buffer.from(value.data, "base64");
  if (
    !bytes.length ||
    bytes.length > MAX_BYTES ||
    bytes.toString("base64") !== value.data ||
    (typed && bytes.length !== value.bytes)
  )
    throw new Error("Attachment size or encoding mismatch");
  const isImage =
    value.type === "image" || (!typed && value.mimeType?.startsWith("image/"));
  if (isImage && imageType(bytes) !== value.mimeType)
    throw new Error("Invalid or unsupported image");
  if (
    value.type === "file" &&
    ["image/png", "image/jpeg", "image/webp", "image/gif"].includes(
      value.mimeType,
    )
  )
    throw new Error("Images must use an image attachment");
  return { bytes, isImage, typed };
}
function extensionFor(mimeType, name) {
  const suffix = path.extname(name || "");
  // Preserve document/archive/source-code suffixes for Agent readers. Names
  // never become paths; every stored basename is generated by this process.
  if (!mimeType.startsWith("image/") && /^\.[a-z0-9]{1,16}$/i.test(suffix))
    return suffix;
  return (
    {
      "image/png": ".png",
      "image/jpeg": ".jpg",
      "image/webp": ".webp",
      "image/gif": ".gif",
      "application/pdf": ".pdf",
      "application/json": ".json",
      "text/plain": ".txt",
      "text/markdown": ".md",
      "text/csv": ".csv",
    }[mimeType] || (/^\.[a-z0-9]{1,16}$/i.test(suffix) ? suffix : ".bin")
  );
}

// Validate the whole payload before writing. No caller-supplied path or URL is read.
// Paths below belong to THIS Agent host, never to the owner's Chrome machine.
function materializeAttachments(result, scope) {
  if (scope?.closed) throw new Error("Attachment task has ended");
  const binaries = [];
  const visit = (value, depth = 0) => {
    if (depth > 32)
      throw new Error("Result nesting exceeds the attachment limit");
    if (!value || typeof value !== "object" || materialized.has(value))
      return value;
    if (Array.isArray(value))
      return value.map((item) => visit(item, depth + 1));
    // A tool may describe a DOM input with type="file" or type="image".
    // Only binary envelopes carry these transport fields.
    const typed =
      (value.type === "image" || value.type === "file") &&
      ("data" in value || "mimeType" in value || "bytes" in value);
    const legacyImage =
      typeof value.mimeType === "string" && value.mimeType.startsWith("image/");
    if (typed || legacyImage) {
      if (binaries.length >= MAX_ITEMS)
        throw new Error("Too many attachments in one request");
      const binary = validateBinary(value);
      const metadata = binary.typed
        ? {
            id: value.id,
            type: value.type,
            name: value.name,
            mimeType: value.mimeType,
          }
        : Object.fromEntries(
            Object.entries(value).filter(([key]) => key !== "data"),
          );
      const output = { ...metadata, bytes: binary.bytes.length };
      binaries.push({ ...binary, output });
      return output;
    }
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, visit(item, depth + 1)]),
    );
  };
  const output = visit(result);
  if (!binaries.length) return output;
  const total = binaries.reduce((n, item) => n + item.bytes.length, 0);
  if (total > MAX_BYTES)
    throw new Error("Attachments exceed the request size limit");

  const dir = obsDir();
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const stored = storedAttachmentBytes();
  if (stored + total > STORE_BYTES)
    throw new Error("Attachment storage is full");
  const created = [];
  try {
    for (const item of binaries) {
      const file = path.join(
        dir,
        "attachment-" +
          Date.now() +
          "-" +
          crypto.randomUUID() +
          extensionFor(item.output.mimeType, item.output.name),
      );
      fs.writeFileSync(file, item.bytes, { mode: 0o600, flag: "wx" });
      created.push(file);
      Object.assign(item.output, {
        path: file,
        ...(item.isImage
          ? { imageReadRequired: true }
          : { fileReadRequired: true }),
      });
      materialized.add(item.output);
    }
  } catch (error) {
    for (const file of created) {
      try {
        fs.unlinkSync(file);
      } catch {
        /* retain the original failure */
      }
    }
    throw error;
  }
  if (scope) for (const file of created) scope.files.add(file);
  return output;
}

// Older callers and nested {mimeType,data} screenshots remain compatible.
export {
  materializeAttachments,
  materializeAttachments as materializeImages,
  ATTACHMENT_CAPABILITY,
  AttachmentScope,
};